<a href="https://colab.research.google.com/github/Akanksha-Ceris/DSA-activity/blob/main/Pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas  as pd
runs = [23,56,78]
pd.Series(runs)

0    23
1    56
2    78
dtype: int64

In [ ]:
# custom index
marks = [45,67,89]
subjects =['math','englis','hindi']
pd.Series(marks,index=subjects)

math      45
englis    67
hindi     89
dtype: int64

In [ ]:
# customer code
marks = [34,56,78]
subjects =['maths','englsh','science']
pd.Series(marks,index=subjects)

maths      34
englsh     56
science    78
dtype: int64

In [ ]:
# setting a name
marks = pd.Series(marks,index = subjects,name = 'Nitish ke marks' )
print(marks)

maths      34
englsh     56
science    78
Name: Nitish ke marks, dtype: int64

Series from dict

In [ ]:
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100
}
marks_series = pd.Series(marks,name ='akanksha ke marks')
marks_series

maths       67
english     57
science     89
hindi      100
Name: akanksha ke marks, dtype: int64

Series Attributes

In [ ]:
# size
marks_series
{ 'maths':67,'english':57,'science': 89,'hindi':100}
print(marks_series.size)

4

In [ ]:
#dtype
marks_series.dtype

dtype('int64')

In [ ]:
# name
marks_series.name

'akanksha ke marks'

In [ ]:
# is_unique
marks_series.is_unique
pd.Series([1,2,1,3,5]).is_unique

False

In [ ]:
#index
marks_series.index

Index(['maths', 'english', 'science', 'hindi'], dtype='object')

In [ ]:
# values
marks_series.values

array([ 67,  57,  89, 100])

# New Section

In [ ]:
import pandas
mydataset = {
    'cars' :["BMW","VOLVO","FORD"],
    'passigns':[3,7,2]

}
myvar = pandas.DataFrame(mydataset)
print(myvar)

    cars  passigns
0    BMW         3
1  VOLVO         7
2   FORD         2

In [ ]:
import pandas as pd

In [ ]:

mydataset = {
    'cars':["BMV","VOLVO","FORD"],
    'passings':[3,7,2]

}
myvar = pd.DataFrame(mydataset)
print(myvar)

    cars  passings
0    BMV         3
1  VOLVO         7
2   FORD         2

In [ ]:
#  date is 5 of march 2026
# crate a simple pandas as pd
import pandas as pd
a = [1,7,2]
myvar = pd.Series(a)
print(myvar)

0    1
1    7
2    2
dtype: int64

In [ ]:
# return the first value of the Series
print(myvar[0])

1

In [ ]:
# create your own labels:
a = [1,7,2]
myvar = pd.Series(a,index = ["x","y","z"])
print(myvar)

x    1
y    7
z    2
dtype: int64

In [ ]:
# when you have created labels , you can access an item by referring to the label
# example:
# return  the value of "y"
print(myvar["y"])

7

 key/Values Objects as Series

In [ ]:
# create a  simple pandas Series from a dictonary:
calories = {"day1":345,"day2":789,"day3":783}
myvar = pd.Series(calories)
print(myvar)
# here the keys of the dictionary become the labels

day1    345
day2    789
day3    783
dtype: int64

In [ ]:
# create  a Series using only data from "day1" and "day2":

myvar = pd.Series(calories,index=["day1","day2"])
print(myvar)

day1    345
day2    789
dtype: int64

DataFrames

Data sets in pandas are usually multi-dimensional tables ,called Dataframes
series is like a column , a DataFrame is the whole table

In [ ]:
# create a Dataframe from  two series
data = {
    "calories":[234,56,789],
    "duration":[50,40,45]
}
myvar = pd.DataFrame(data)
print(myvar)

   calories  duration
0       234        50
1        56        40
2       789        45

Locate Row

What is Dataframe?
A pandas Dataframe is a 2 dimensional data structure ,like a 2 dimensional array, or a table with rows and columns.

In [ ]:
# Create a simple Pandas Dataframe
data = {
    "colories":[789,34,56],
    "duration":[56,34,56]

    }
    #load data into a Dataframe objects:
df = pd.DataFrame(data)
print(df)

   colories  duration
0       789        56
1        34        34
2        56        56

In [ ]:
# use a list of indexes:
print(df.loc[[0,1]])

   colories  duration
0       789        56
1        34        34

# Named Indexes

In [ ]:
# with the index argunment , you can  name your own indexes
# Add a list of names to give each row a name:
data = {
    "calories":[420,380,390],
    "duration":[50,40,45]
}
df = pd.DataFrame(data,index=["day1","day2","day3"])
print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45

Locate

Load Files into a DataFrame
If your data sets are stored in a file, Pandas can load them into  a DataFRame

In [ ]:
# Load a comma deparated file(CSV file ) into a Dataframe

In [ ]:
import pandas as pd

Series using read_csv

In [ ]:
# with one col

Series using read_csv

In [ ]:
# with one col
subs=pd.read_csv('/content/subs.csv').squeeze("columns")
subs

FileNotFoundError: [Errno 2] No such file or directory: '/content/subs.csv'

In [ ]:
# with 2 cols
vk =pd.read_csv('/content/kohli_ipl.csv',index_col='match_no').squeeze("columns")
print(vk)

FileNotFoundError: [Errno 2] No such file or directory: '/content/kohli_ipl.csv'

Series methods

In [ ]:
# head and tail
# it provide top 5 rows of dataseet
subs.head()

0    48
1    57
2    40
3    43
4    44
Name: Subscribers gained, dtype: int64

In [ ]:
vk.head(3)

match_no
1     1
2    23
3    13
Name: runs, dtype: int64

In [ ]:
# Tail
vk.tail()

match_no
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

In [ ]:
# it provide last 10 matches of ipl
vk.tail(10)

match_no
206     0
207     0
208     9
209    58
210    30
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

In [ ]:
# sample. it select  columns randomly
vk.sample()

match_no
63    45
Name: runs, dtype: int64

In [ ]:
# show randomly 5 columns from the dataset
vk.sample(5)

match_no
208     9
173    29
103    51
35      3
131    54
Name: runs, dtype: int64

In [ ]:
# value counts
cars=pd.read_csv('/content/cars.csv')
cars

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [ ]:
vk.value_counts()

runs
0     9
1     8
12    8
9     7
8     6
     ..
46    1
29    1
84    1
90    1
53    1
Name: count, Length: 78, dtype: int64

In [ ]:
# sort values4# method chaning
vk.sort_values(ascending = False).head(1).values[0]

np.int64(113)

In [ ]:
cars.sort_index()

NameError: name 'cars' is not defined

In [ ]:
# sort_index -> inplace -> movies
cars.sort_index(inplace = True)
cars

NameError: name 'cars' is not defined

In [ ]:
# Data cleaning : missing values,invalid values

In [ ]:
# size mutability

In [ ]:
# statical analysis

In [ ]:
# programming language _python
# math:statics

In [2]:
# primary data structure
# 1 series: 1D
#2 DataFRame  2 D

In [51]:
import pandas as pd

In [6]:
s = pd.Series ([12,45,67,88])
print(s)

0    12
1    45
2    67
3    88
dtype: int64

In [ ]:
s

In [5]:
s.dtype

dtype('int64')

In [ ]:
s.values

array([12, 45, 67, 88])

In [ ]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
s.name

In [50]:
print(s.name)

None

In [7]:
s.name="numbers"
s

0    12
1    45
2    67
3    88
Name: numbers, dtype: int64

In [8]:
# Indexing

In [9]:
s[0]

np.int64(12)

In [ ]:
# If i want multiple element

In [4]:
s[0:2]# # start(included): stop (excluded):step value (value to jump)

NameError: name 's' is not defined

In [ ]:
s[2:4]

2    67
3    88
Name: numbers, dtype: int64

In [7]:
#iloc -> location based indexing
s.iloc[3]

np.int64(88)

In [ ]:
s.iloc[[0,1,2]]

0    12
1    45
2    67
Name: numbers, dtype: int64

In [ ]:
s.name = "claories"# I have changed the column  name to colories
s

0    12
1    45
2    67
3    88
Name: claories, dtype: int64

In [9]:
index = ["apple","banana","grapes","orange"]
s.index= index
s

apple     12
banana    45
grapes    67
orange    88
dtype: int64

In [ ]:
s['grapes']

np.int64(67)

In [ ]:
s.iloc[3]

np.int64(88)

In [ ]:
#loc -> label based indexing
s.loc['grapes']

np.int64(67)

In label based indexing your start as well as stop value both are included in the output

In [11]:
print(s)

apple     12
banana    45
grapes    67
orange    88
Name: numbers, dtype: int64

In [10]:
s["apple":"ornage"]

apple     12
banana    45
grapes    67
orange    88
dtype: int64

In [11]:
# how i can create series using dictionary
fruit_protien = {
    "Avocado":2.0,
    "Guava":2.6,
    "Blackberries":2.0, # grams of protein
    "Oranges":0.9,
    "Banana":1.1,
    "kiwi":1.1,
    "Pomeogranate":1.7,
    "Mango":0.8,
    "Cherries":1.0

}

In [12]:
s2 = pd.Series(fruit_protien)
name = "protein"
print(s2)

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
kiwi            1.1
Pomeogranate    1.7
Mango           0.8
Cherries        1.0
dtype: float64

In [13]:
# conditional selection
# i want to   find the protien_fruit which is greater than 1
s2>1

Avocado          True
Guava            True
Blackberries     True
Oranges         False
Banana           True
kiwi             True
Pomeogranate     True
Mango           False
Cherries        False
dtype: bool

In [14]:
s2[s2>1]

Avocado         2.0
Guava           2.6
Blackberries    2.0
Banana          1.1
kiwi            1.1
Pomeogranate    1.7
dtype: float64

In [15]:
# Logical Operator.# and operator
[(s2>0.5) & (s2>2)]

[Avocado         False
 Guava            True
 Blackberries    False
 Oranges         False
 Banana          False
 kiwi            False
 Pomeogranate    False
 Mango           False
 Cherries        False
 dtype: bool]

In [16]:
# or operator
s2[(s2>0.5) |  (s2 <= 2)]

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
kiwi            1.1
Pomeogranate    1.7
Mango           0.8
Cherries        1.0
dtype: float64

In [17]:
# not operator
s2[~(s2>1)]

Oranges     0.9
Mango       0.8
Cherries    1.0
dtype: float64

In [18]:
# modifying the series:
s2 ["mango" ] = 2.8
s2

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
kiwi            1.1
Pomeogranate    1.7
Mango           0.8
Cherries        1.0
mango           2.8
dtype: float64

In [52]:
import numpy as np

In [53]:
ser = pd.Series(['a',np.nan,1,np.nan,2])
s.notnull().sum()

np.int64(4)

In [22]:
data = {
    "Name":["Alice","Bob","Charlie","David","Eve","Alice"],
    "Age" :[25,30,35,np.nan,29,25],
    "Department":["HR","IT","Finanace","IT","HR","HR"], # dataframe

    "Salary":[50000,60000,70000,62000,np.nan,50000]
}

In [54]:
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finanace', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [24]:
df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0   Finanace  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [25]:
df.head(2)

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0

In [26]:
df.tail(2)

    Name   Age Department   Salary
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

In [ ]:
# loc and iloc\
df.iloc[1:3]

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0   Finanace  70000.0

In [ ]:
df.loc[1:2,["Age","Department"]] # rows

    Age Department
1  30.0         IT
2  35.0   Finanace

In [ ]:
df["Age"]

0    25.0
1    30.0
2    35.0
3     NaN
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df[["Age","Department"]]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0   Finanace
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [18]:
df.drop("Age",axis = 1,inplace = True)

In [27]:
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finanace', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [28]:
df.head(2)

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0

In [30]:
df.tail(3)

    Name   Age Department   Salary
3  David   NaN         IT  62000.0
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

In [31]:
# loc and iloc
df.iloc[1:3]

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0   Finanace  70000.0

In [36]:
df.loc[1:3,["Age","Department"]]

    Age Department
1  30.0         IT
2  35.0   Finanace
3   NaN         IT

In [37]:
df.iloc[1:3, :2]# rows ,column

      Name   Age
1      Bob  30.0
2  Charlie  35.0

In [39]:
df[["Age","Department"]]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0   Finanace
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [40]:
# drop age column
df.drop("Age",axis = 1)

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie   Finanace  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [41]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0   Finanace  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [43]:
# shpe of dataset
df.shape

(6, 4)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [45]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

In [56]:
df["Salary"]

0    50000.0
1    60000.0
2    70000.0
3    62000.0
4        NaN
5    50000.0
Name: Salary, dtype: float64

In [58]:
#Broadcasting
df["Salary"] = df["Salary"] + 5000

In [59]:
df["Salary"]

0    60000.0
1    70000.0
2    80000.0
3    72000.0
4        NaN
5    60000.0
Name: Salary, dtype: float64

In [61]:
# Renaiming columns:
df.rename(columns={"Department": "Dept"},inplace = True)

In [62]:
df["Dept"].unique()

array(['HR', 'IT', 'Finanace'], dtype=object)

In [63]:
df["Dept"].value_counts()

Dept
HR          3
IT          2
Finanace    1
Name: count, dtype: int64

In [65]:
df["Promoted Salary"] = df["Salary"] * 10
df

      Name   Age      Dept   Salary  Promoted Salary
0    Alice  25.0        HR  60000.0         600000.0
1      Bob  30.0        IT  70000.0         700000.0
2  Charlie  35.0  Finanace  80000.0         800000.0
3    David   NaN        IT  72000.0         720000.0
4      Eve  29.0        HR      NaN              NaN
5    Alice  25.0        HR  60000.0         600000.0

In [ ]:
# data cleaning

In [67]:
df.isnull().sum()

Name               0
Age                1
Dept               0
Salary             1
Promoted Salary    1
dtype: int64

In [69]:
# Missing values
df.fillna(0)

      Name   Age      Dept   Salary  Promoted Salary
0    Alice  25.0        HR  60000.0         600000.0
1      Bob  30.0        IT  70000.0         700000.0
2  Charlie  35.0  Finanace  80000.0         800000.0
3    David   0.0        IT  72000.0         720000.0
4      Eve  29.0        HR      0.0              0.0
5    Alice  25.0        HR  60000.0         600000.0

In [74]:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [75]:
df["Salary"].fillna(df["Salary"].median())

0    60000.0
1    70000.0
2    80000.0
3    72000.0
4    70000.0
5    60000.0
Name: Salary, dtype: float64

In [76]:
df["Age"].fillna(method = "ffill")

/tmp/ipykernel_543/544980945.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "ffill")

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [77]:
df["Age"].fillna(method = "bfill")

/tmp/ipykernel_543/3026805218.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "bfill")

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [80]:
df["Name"]=df["Name"].replace("Charlie","Rose")
df

    Name   Age      Dept   Salary  Promoted Salary
0  Alice  25.0        HR  60000.0         600000.0
1    Bob  30.0        IT  70000.0         700000.0
2   Rose  35.0  Finanace  80000.0         800000.0
3  David  28.8        IT  72000.0         720000.0
4    Eve  29.0        HR      NaN              NaN
5  Alice  25.0        HR  60000.0         600000.0

In [83]:
# how  to deal with duplicate  values
df_dup = df[df.duplicated(keep = "first")]
df_dup

    Name   Age Dept   Salary  Promoted Salary
5  Alice  25.0   HR  60000.0         600000.0

In [84]:
df_dump = df[df.duplicated(keep = "last")]
df_dump

    Name   Age Dept   Salary  Promoted Salary
0  Alice  25.0   HR  60000.0         600000.0

In [86]:
df = df.drop_duplicates()
df

    Name   Age      Dept   Salary  Promoted Salary
0  Alice  25.0        HR  60000.0         600000.0
1    Bob  30.0        IT  70000.0         700000.0
2   Rose  35.0  Finanace  80000.0         800000.0
3  David  28.8        IT  72000.0         720000.0
4    Eve  29.0        HR      NaN              NaN

In [88]:
# invaalid values:
# Lambda -> python
df["promoted salary"] =  df["Promoted Salary"].apply(lambda x: x /10 if x > 650000 else x)

In [98]:
name = "alice_fernandes"
df[["first_name","last_name"]] = df["name"].str.split("_")

KeyError: 'name'

In [97]:
# apply and lambda
def multiplying_age(x):
   return x*2
df["Age"] = df["Age"].apply(multiplying_age)
df

    Name     Age      Dept   Salary  Promoted Salary  promoted salary
0  Alice  1600.0        HR  60000.0         600000.0         600000.0
1    Bob  1920.0        IT  70000.0         700000.0          70000.0
2   Rose  2240.0  Finanace  80000.0         800000.0          80000.0
3  David  1843.2        IT  72000.0         720000.0          72000.0
4    Eve  1856.0        HR      NaN              NaN              NaN

Joins and Merges

In [101]:
department_info = {
  "Department":["HR","IT","Finance"],
  "Location":["New York","San Francisco","Chicago"],
  "Manager":["Laura","Steve","Nina"]}
df2 = pd.DataFrame(department_info)
df2

  Department       Location Manager
0         HR       New York   Laura
1         IT  San Francisco   Steve
2    Finance        Chicago    Nina

In [103]:
pd.concat([df,df2])

,Name,Age,Dept,Salary,Promoted Salary,promoted salary,Department,Location,Manager
0,Alice,1600.0,HR,60000.0,600000.0,600000.0,NaN,NaN,NaN
1,Bob,1920.0,IT,70000.0,700000.0,70000.0,NaN,NaN,NaN
2,Rose,2240.0,Finanace,80000.0,800000.0,80000.0,NaN,NaN,NaN
3,David,1843.2,IT,72000.0,720000.0,72000.0,NaN,NaN,NaN
4,Eve,1856.0,HR,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,HR,New York,Laura
1,NaN,NaN,NaN,NaN,NaN,NaN,IT,San Francisco,Steve
2,NaN,NaN,NaN,NaN,NaN,NaN,Finance,Chicago,Nina

In [105]:
pd.merge(df,df2,on = "Dept")

KeyError: 'Dept'

In [ ]:
data = pd.read("datascvfile")
# head give gives first 5 rows of dataset

In [106]:
# data shape: it gives the rows and column